### ISSUE TITLE
Unexpected error while executing task in windows 10

### ISSUE THREAD

**Issue by muzaluisa** [readbeyond/aeneas#212] opened 2018-08-27 14:40 UTC
Hey, I am having Windows 10 and installed aeneas 1.7.3 using .exe installation file officially provided
This is the folder with my data
https://www.dropbox.com/sh/na5q6woags9lmyq/AAA8kl7eGCWkvPakrOmaT7-ra?dl=0

When I run via command line
`python -m aeneas.tools.execute_task 2008-09-11.mp3 2008-09-11_cleaned.transcript "task_language=fin|is_text_type=plain|os_task_file_format=json" result_plain.json`

and get the following error:

[INFO] Validating config string (specify --skip-validator to bypass)...
[INFO] Validating config string... done
[INFO] Creating task...
[INFO] Creating task... done
[INFO] Executing task...
[ERRO] An unexpected error occurred while executing the task:
[ERRO] Unexpected error while executing task :

Could you please help me to debug the code?

**Comment by pettarin** [comment] 2018-08-27 20:45
Hi, I am not sure what the problem exactly is, but since your audio file is pretty long, I suspect you saturated the RAM of your machine.

On my laptop, running Linux and with 16 GB, it produced the attached output file in less than 1 minute. (I have no idea whether the alignment is good or not.)

For sure you need at least 8 GB of RAM on your PC, because I watched htop while aeneas was running, and it peaked at about 6 GB.

Also note that Windows is not officially supported, as I personally own only Linux machines and a Mac Mini. The Windows installer were contributed by Daniel Bair and/or SIL staff.

[result_plain.json.zip](https://github.com/readbeyond/aeneas/files/2325556/result_plain.json.zip)

**Comment by pettarin** [comment] 2018-08-27 20:54
It might be also a duplicate of #190 or #172 .

**Comment by muzaluisa** [comment] 2018-08-28 11:12
Hi, 
Apparently indeed the question is a dublicate. I tried to change the version to 1.7.2, but got the same problem. Do you know why the linux installation why using 2 commands for installation has "unable to load python c expensions problem"? Otherwise linux works indeed with the same file :)
Besides, what are the parameters, that I can try to improve the alignment results?

**Comment by readbeyond** [comment] 2018-09-04 20:45
Hi,

if you get the "unable to load etc." error (side note: please 
copy-and-paste the entire error message next time), it probably means 
that you do not have e.g. the libespeak-dev package installed.

Please read here: 
https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#linux

You can test with:

$ python -m aeneas.diagnostics

it should print something like:

[INFO] ffprobe        OK
[INFO] ffmpeg         OK
[INFO] espeak         OK
[INFO] aeneas.tools   OK
[INFO] shell encoding OK
[INFO] aeneas.cdtw    AVAILABLE
[INFO] aeneas.cmfcc   AVAILABLE
[INFO] aeneas.cew     AVAILABLE
[INFO] All required dependencies are met and all available Python C 
extensions are working

or please copy-paste the exact output.


For the parameters, you can have a look at the documentation:

https://www.readbeyond.it/aeneas/docs/

and in particular:

https://www.readbeyond.it/aeneas/docs/clitutorial.html

https://www.readbeyond.it/aeneas/docs/clitutorial.html#listing-parameter-names-and-values

https://www.readbeyond.it/aeneas/docs/clitutorial.html#the-runtime-configuration

https://www.readbeyond.it/aeneas/docs/runtimeconfiguration.html

and possibly also:

https://github.com/readbeyond/aeneas#a-note-on-word-level-alignment

HTH,

Alberto Pettarin

**Comment by Lakshyasukhralia** [comment] 2018-09-18 10:56
Works fine for me by splitting the file.A log file would be appreciated.

**Closed** 2018-10-11 21:36 UTC
