### ISSUE TITLE
The job cannot be loaded from the specified container

### ISSUE THREAD

**Issue by bennylin** [readbeyond/aeneas#8] opened 2015-09-21 14:28 UTC
This is the result from my execute_job test. I couldn't find what's causing the problem.
It worked when it was tested on Unix machine, but on Windows 7 64-bit it doesn't work. 
Fresh installation of Python 2.7.10 (+BeautifulSoup and lxml), ffmpeg-20150916, espeak-1.48.04, numpy-1.9.2+mkl-cp27, scikits.audiolab-0.11.0-cp27, and VCForPython27.msi

c:\sync\aeneas-master>python -m aeneas.tools.execute_job test/01.zip output/ -v
[INFO] Loading job from container...
[DEBU] 2015-09-21 21:20:38.113000 ExecuteJob: Loading job from container...
[DEBU] 2015-09-21 21:20:38.113000 ExecuteJob: Validating container...
[DEBU] 2015-09-21 21:20:38.113000 Validator: Checking container file 'test/01.zip'
[DEBU] 2015-09-21 21:20:38.128000 Validator: Checking container file exists
[DEBU] 2015-09-21 21:20:38.128000 Validator: Checking container file has config file
[DEBU] 2015-09-21 21:20:38.128000 Validator: Container has TXT config file
[DEBU] 2015-09-21 21:20:38.128000 Validator: Checking container with TXT config file
[DEBU] 2015-09-21 21:20:38.128000 Validator: Trying to read config file from con tainer
[DEBU] 2015-09-21 21:20:38.144000 Validator: Config file found in container
[DEBU] 2015-09-21 21:20:38.144000 Validator: Checking contents TXT config file
[DEBU] 2015-09-21 21:20:38.144000 Validator: Converting file contents to config string
[DEBU] 2015-09-21 21:20:38.144000 Validator: Checking that string is well encode d
[DEBU] 2015-09-21 21:20:38.144000 Validator: Checking that the given string is w ell encoded
[DEBU] 2015-09-21 21:20:38.144000 Validator: Checking encoding of string
[DEBU] 2015-09-21 21:20:38.144000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.144000 Validator: Checking for reserved characters
[DEBU] 2015-09-21 21:20:38.144000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.144000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.144000 Validator: Checking required parameters
[DEBU] 2015-09-21 21:20:38.160000 Validator: Checking required parameters '['is_ hierarchy_type', 'is_hierarchy_prefix', 'is_text_file_relative_path', 'is_text_file_name_regex', 'is_text_type', 'is_audio_file_relative_path', 'is_audio_file_name_regex', 'os_job_file_name', 'os_job_file_container', 'os_job_file_hierarchy_ type', 'os_job_file_hierarchy_prefix', 'os_task_file_name', 'os_task_file_format ', 'job_language']'
[DEBU] 2015-09-21 21:20:38.285000 Validator: Checking required parameters
[DEBU] 2015-09-21 21:20:38.300000 Validator: Checking input parameters are not empty
[DEBU] 2015-09-21 21:20:38.332000 Validator: Checking no required parameter is missing
[DEBU] 2015-09-21 21:20:38.378000 Validator: Checking all parameter values are allowed
[DEBU] 2015-09-21 21:20:38.410000 Validator: Checking allowed values for parameter 'job_language'
[DEBU] 2015-09-21 21:20:38.457000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.472000 Validator: Checking allowed values for parameter 'task_language'
[DEBU] 2015-09-21 21:20:38.519000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.535000 Validator: Checking allowed values for parameter 'os_job_file_container'
[DEBU] 2015-09-21 21:20:38.582000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.597000 Validator: Checking allowed values for parameter 'is_hierarchy_type'
[DEBU] 2015-09-21 21:20:38.644000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.660000 Validator: Checking allowed values for parameter 'os_job_file_hierarchy_type'
[DEBU] 2015-09-21 21:20:38.707000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.722000 Validator: Checking allowed values for parameter 'is_text_type'
[DEBU] 2015-09-21 21:20:38.753000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.785000 Validator: Checking allowed values for parameter 'os_task_file_format'
[DEBU] 2015-09-21 21:20:38.816000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.847000 Validator: Checking allowed values for parameter 'task_adjust_boundary_algorithm'
[DEBU] 2015-09-21 21:20:38.878000 Validator: Passed
[DEBU] 2015-09-21 21:20:38.910000 Validator: Checking all implied parameters are present
[DEBU] 2015-09-21 21:20:38.941000 Validator: Checking implied parameters by 'is_hierarchy_type'='paged'
[DEBU] 2015-09-21 21:20:38.988000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.003000 Validator: Checking implied parameters by 'is_text_type'='unparsed'
[DEBU] 2015-09-21 21:20:39.050000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.066000 Validator: Checking implied parameters by 'is_text_type'='unparsed'
[DEBU] 2015-09-21 21:20:39.113000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.128000 Validator: Checking implied parameters by 'os_task_file_format'='smil'
[DEBU] 2015-09-21 21:20:39.160000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.191000 Validator: Checking implied parameters by 'os_task_file_format'='smil'
[DEBU] 2015-09-21 21:20:39.222000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.238000 Validator: Checking implied parameters by 'task_adjust_boundary_algorithm'='percent'
[DEBU] 2015-09-21 21:20:39.285000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.300000 Validator: Checking implied parameters by 'task_adjust_boundary_algorithm'='rate'
[DEBU] 2015-09-21 21:20:39.347000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.363000 Validator: Checking implied parameters by 'task_adjust_boundary_algorithm'='rateaggressive'
[DEBU] 2015-09-21 21:20:39.394000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.425000 Validator: Checking implied parameters by 'task_adjust_boundary_algorithm'='aftercurrent'
[DEBU] 2015-09-21 21:20:39.457000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.472000 Validator: Checking implied parameters by 'task_adjust_boundary_algorithm'='beforenext'
[DEBU] 2015-09-21 21:20:39.519000 Validator: Passed
[DEBU] 2015-09-21 21:20:39.550000 Validator: Checking required parameters: returning True
[DEBU] 2015-09-21 21:20:39.582000 Validator: Checking contents TXT config file: returning True
[DEBU] 2015-09-21 21:20:39.628000 Validator: Analyze the contents of the container
[DEBU] 2015-09-21 21:20:39.675000 Validator: Checking the Job object generated from container
[DEBU] 2015-09-21 21:20:39.722000 Validator: Checking the Job is not None
[DEBU] 2015-09-21 21:20:39.738000 Validator: Checking the Job has at least one Task
[DEBU] 2015-09-21 21:20:39.785000 Validator: Unable to create at least one Task from the container.
[DEBU] 2015-09-21 21:20:39.816000 Validator: Checking container with TXT config file: returning False
[DEBU] 2015-09-21 21:20:39.863000 Validator: Checking container: returning False
[DEBU] 2015-09-21 21:20:39.894000 ExecuteJob: Validating container: failed
[DEBU] 2015-09-21 21:20:39.925000 ExecuteJob: Loading job from container: failed
[INFO] Loading job from container... done [ERRO] The job cannot be loaded from the specified container

Config:

is_hierarchy_type=flat
is_hierarchy_prefix=input/
is_text_file_relative_path=.
is_text_file_name_regex=.*\.txt
is_text_type=parsed
is_audio_file_relative_path=.
is_audio_file_name_regex=.*\.MP3

os_job_file_name=output_test-01
os_job_file_container=zip
os_job_file_hierarchy_type=flat
os_job_file_hierarchy_prefix=input/
os_task_file_name=$PREFIX.smil
os_task_file_format=smil
os_task_file_smil_page_ref=$PREFIX.xhtml
os_task_file_smil_audio_ref=$PREFIX.mp3

job_language=en
job_description=Test 01 (flat hierarchy, parsed text files)

**Comment by pettarin** [comment] 2015-09-21 20:24
Hi, it sounds strange that the same ZIP file, when read on Unix produces a valid Job, while on Windows it does not.

Have you tried uncompressing the ZIP file, and then running `execute_task` providing the path to the uncompressed directory? Does it work?

If you can share the ZIP file (if you prefer keeping it private, email it to aeneas@readbeyond.it ), I might give it a look.

**Comment by readbeyond** [comment] 2015-10-15 11:22
Any news on this issue? Did you solve it? If not, try upgrading to v1.3.0 and see if the issue is still there.

If you cloned aeneas with git on Windows, beware of symlinks: https://groups.google.com/d/msg/aeneas-forced-alignment/p9cb1FA0X0I/HFlHB2gRBgAJ

**Comment by readbeyond** [comment] 2015-11-16 10:09
Closing as more than a month passed without any comment.

**Closed by readbeyond** 2015-11-16 10:09 UTC

**Comment by bennylin** [comment] 2015-11-16 10:47
Thanks. The bug was resolved by my teammate.

**Comment by readbeyond** [comment] 2015-11-16 15:27
Sure, no problem. Was it a bug in `aeneas` or a problem due to your execution environment? If the former (a bug in `aeneas`), would you mind suggesting what the root cause was, so that we can fix it?

**Comment by bennylin** [comment] 2015-11-16 16:43
I believe something was not set up correctly in the settings, and it was not a bug. Thanks for the great program! :)

**Comment by readbeyond** [comment] 2015-11-17 12:40
You are welcome. Thank you for taking time to confirm the issue is solved.
